baseurl = "https://example.org/"
languageCode = "en-us"
theme = "light-hugo"

title = "Saulo Said"
author = "Saulo Said"
copyright = "© Copyright 2016 John Doe"

[Params]
  description = "Tableau, Dataviz, futebol, economia e política"
  email = "saidsaulo@gmail.com"
  github = "SauloSaid"
#  twitter = ""
  linkedin = "saulo-said-b43356a1/"
#  facebook = "johndoe"
  logo = "/images/logo.png"
